version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      -echo "installing dependencies..."
      -pip instal -r requirements.txt -t lib
    build:
      commands:
        -echo "Zipping deployment paakage..."
        -cd lib
        -zip -r9 ../deployment_package.zip .
        -cd ..
        -zip -g deployment_package.zip lambda_function.py
      post_build:
        commands:
          -echo "Updating Lambda Function..."
          -aws lambda update-function-code --function-name githubtolambdademo --zip-file fileb://deployment_package.zip
          -echo "Done!!"
